name: CI Workflow

on: [push]

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            target: dev@wsl
          # - os: macos-latest
          #   profile: dev@mac

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Apply Home Manager Configuration
        shell: bash
        run: |
          nix shell nixpkgs#home-manager
          home-manager --extra-experimental-features "nix-command flakes" --flake .#${{ matrix.config.target }} switch --impure
