name: CI Workflow

on: [push]

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            target: minimal@linux
          - os: ubuntu-latest
            target: minimal@mac

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Apply Home Manager Configuration
        shell: bash
        run: |
          nix run home-manager/master -- switch --extra-experimental-features "nix-command flakes" --flake .#${{ matrix.config.target }} --impure
