name: CI Workflow

on: [push]

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            home_manager_command: 'home-manager --extra-experimental-features "nix-command flakes" --flake .#dev@wsl switch --impure'
          - os: macos-latest
            home_manager_command: 'home-manager --extra-experimental-features "nix-command flakes" --flake .#dev@mac switch --impure'

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Install Home Manager
        shell: bash
        run: nix profile install nixpkgs#home-manager

      - name: Apply Home Manager Configuration
        shell: bash
        run: |
          ${{ matrix.config.home_manager_command }}
