name: linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Cache for Nix Store
      - name: Cache Nix Store
        uses: actions/cache@v3
        with:
          path: /nix/store
          key: nix-store-${{ runner.os }}-${{ hashFiles('.config/home-manager/home.nix') }}
          restore-keys: |
            nix-store-${{ runner.os }}-

      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          echo "source ~/.nix-profile/etc/profile.d/nix.sh" >> $HOME/.bashrc

      - name: Cache Nix Profiles
        uses: actions/cache@v3
        with:
          path: ~/.nix-profile
          key: nix-profile-${{ runner.os }}-${{ hashFiles('.config/home-manager/home.nix') }}
          restore-keys: |
            nix-profile-${{ runner.os }}-

      - name: Install Home Manager
        shell: bash
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
          nix-channel --update
          nix-shell '<home-manager>' -A install

      - name: Apply Home Manager Configuration
        shell: bash
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          home-manager switch --file .config/home-manager/home.nix

      - name: Run init.sh
        shell: bash
        run: |
          source ~/.nix-profile/etc/profile.d/nix.sh
          ./init.sh

      - name: Check init.sh
        run: shellcheck ${GITHUB_WORKSPACE}/init.sh
