name: linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          source ~/.nix-profile/etc/profile.d/nix.sh

      - name: Install Home Manager
        run: |
          nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
          nix-channel --update
          nix-shell '<home-manager>' -A install

      - name: Apply Home Manager Configuration
        run: |
          home-manager switch --file .config/home-manager/home.nix

      - name: Run init.sh
        run: ./init.sh

      - name: Check init.sh
        run: shellcheck ${GITHUB_WORKSPACE}/init.sh
