name: macos

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - run: brew unlink go@1.21

      - name: Run brew bunlde
        run: brew bundle

      - name: Run init.sh
        run: ./init.sh
