name: macos

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run brew bunlde
        run: brew bundle
        continue-on-error: true

      - name: Run init.sh
        run: ./init.sh
