name: macos

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run brew bunlde
        run: brew bundle

      - name: Run init.sh
        run: ./init.sh

      - name: Check init.sh
        run: shellcheck ${GITHUB_WORKSPACE}/init.sh
