name: CI

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        config:
          - os: macos-15

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31

      - name: Apply Configuration
        shell: bash
        run: sudo nix --extra-experimental-features "nix-command flakes" run nix-darwin -- switch --flake .#mac --impure
