on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Apply Configuration
        shell: bash
        run: nix run nix-darwin -- switch --flake .#mac --impure
