name: test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # https://qiita.com/access3151fq/items/c31671934906cc73f541
      - name: Setup Homebrew
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
          sudo apt-get install build-essential

      - name: Run brew bunlde
        run: brew bundle

      - name: Run init.sh
        run: ./init.sh
